-
  branches:
    only:
      - master
  configuration: Release
  environment:
    nuget_api_key:
      secure: oRzXYnLhiuEhrTafW4jGry9+IRoscwyh48Rpq5CDNoupclJEktj6J97aVatWxdN+
  version: 1.0.{build}
  before_build:
  - nuget restore
  build:
    project: fluent-mapper.sln
    verbosity: minimal
  after_build:
  - nuget pack -Version %APPVEYOR_BUILD_VERSION% FluentMapping\FluentMapping.csproj
  test:
    assemblies:
      - '**\*.tests.dll'
  on_success:
  - nuget push FluentMapper.%APPVEYOR_BUILD_VERSION%.nupkg -ApiKey %nuget_api_key% -Verbosity detailed
  
-
  version: 1.0.{build}
  before_build:
  - nuget restore
  build:
    project: fluent-mapper.sln
    verbosity: minimal
  test:
    assemblies:
      - '**\*.tests.dll'
