-
  branches:
    only:
      - master
  configuration: Release
  version: 1.0.{build}
  before_build:
  - nuget restore
  build:
    project: fluent-mapper.sln
    verbosity: minimal
  after_build:
  - nuget pack FluentMapping\FluentMapping.csproj
  test:
    assemblies:
      - '**\*.tests.dll'
  deploy:
    provider: NuGet
    api_key:
      secure: oRzXYnLhiuEhrTafW4jGry9+IRoscwyh48Rpq5CDNoupclJEktj6J97aVatWxdN+
    skip_symbols: true
    artifact: /.*\.nupkg/

-
  version: 1.0.{build}
  before_build:
  - nuget restore
  build:
    project: fluent-mapper.sln
    verbosity: minimal
  test:
    assemblies:
      - '**\*.tests.dll'
